### ISSUE TITLE
improvement: excessive logging from security hub

### ISSUE THREAD

**Issue by kalleeh** [kalleeh/aws-msb#1]
Currently the alerts are spamming the notification e-mail with too many alerts from Security Hub.
This is because there are no simple way to filter the "PASSED" checks and only forward findings that have a compliance status of "FAILED".

Preferably this can be implemented as an extension to the CloudWatch Event Rule similar to below although the rule format doesn't support this.

```yaml

source:
  - aws.securityhub
detail-type:
  - Security Hub Findings - Imported
detail-type:
  findings:
    -
      Compliance:
        Status: "FAILED"
```

Other options are to add a Lambda function only to filter those fields and then pass it to the SNS topic.
Also consider looking into SNS Subscription filters?
